print("Hello World")
print("Hello Again")
print("                ___       ___")
print("               /   \ ~~~ /   \\")
print("         ,----(       ..      ")
print("        /      \___       ___/")
print("       /|          (\   |(")
print("      ^ \    /___\  /\  | ")
print("         |__|    |__|-''")
print("")
print("")
print("")
print("")
print("           _")
print("          ( \\")
print("           ) )")  
print("          ( (   .-''''-.   A.-.A    ")
print("           \ \/         \/  , , \ ")
print("            \    \      =;   t  /=")
print("             \    |''''.  ' ,--'  ")
print("              /  //    | ||")
print("             /_, ))    |_,))")
print("      ")
print("      ")
print("      ")
print("         \_\_    _/_/")
print("             \__/ ")
print("             (oo)\________")
print("             (__)\        )\/\ ")
print("                 ||-----||     ")
print("                 ||     ||      ")
